---
# Download paths
openwrt_feed: "releases"   # "releases" or "snapshots"
openwrt_dl_base: 'https://downloads.openwrt.org/{{ openwrt_feed }}/{{ openwrt_release }}/targets/{{ openwrt_arch }}/{{ openwrt_cpu }}'

# Controller/target paths
openwrt_download_dir: "/tmp"   # controller temp dir
openwrt_remote_tmp: "/tmp"     # target temp dir

# Filenames
openwrt_kernel_image: 'openwrt-{{ openwrt_release }}-{{ openwrt_arch }}-{{ openwrt_cpu }}-{{ openwrt_model }}-initramfs-kernel.bin'
openwrt_sysupgrade_image: 'openwrt-{{ openwrt_release }}-{{ openwrt_arch }}-{{ openwrt_cpu }}-{{ openwrt_model }}-squashfs-sysupgrade.bin'

# Upgrades
openwrt_sysupgrade_typical_size_mb: 8
openwrt_force_upgrade: false
reboot_timeout: 600

# Suggested by ChatGPT. Not sure if I will implement this. 
# Sysupgrade behavior
# openwrt_keep_config: true       # sysupgrade keeps config by default; -n disables
# openwrt_keep_packages: false    # use -k to try preserving installed pkgs (may not be desired)
# openwrt_sysupgrade_flags: >-
#   {{ '' }}
#   {{ '' if openwrt_keep_config else '-n' }}
#   {{ ' -k' if openwrt_keep_packages else '' }}
#   {{ ' -v' }}

# SSH
ssh_opts: ''

# System configuration defaults
openwrt_ntp_enable_server: '0'
openwrt_timezone: 'UTC'
openwrt_zonename: 'UTC'
openwrt_ntp_servers:
  - '0.openwrt.pool.ntp.org'
  - '1.openwrt.pool.ntp.org'
  - '2.openwrt.pool.ntp.org'
  - '3.openwrt.pool.ntp.org'